 ren c1 JS_FLEX_SCHED_TA_reduced
ren c2 JS_FLEX_SCHED_TA_unchanged
ren c3 JS_FLEX_SCHED_TA_increased
ren c4 JS_NIGHTS_REG_TA_reduced
ren c5 JS_NIGHTS_REG_TA_unchanged
ren c6 JS_NIGHTS_REG_TA_increased
ren c7 JS_L_HOURS_REG_TA_reduced
ren c8 JS_L_HOURS_REG_TA_unchanged
ren c9 JS_L_HOURS_REG_TA_increased
ren c10 JS_WEEKEND_TA_reduced
ren c11 JS_WEEKEND_TA_unchanged
ren c12 JS_WEEKEND_TA_increased
ren c13 JS_LONG_FLEX_TA_reduced
ren c14 JS_LONG_FLEX_TA_unchanged
ren c15 JS_LONG_FLEX_TA_increased
ren c16 JS_SUN_NIGHTS_TA_reduced
ren c17 JS_SUN_NIGHTS_TA_unchanged
ren c18 JS_SUN_NIGHTS_TA_increased
