ren c1 JS_FLEX_SCHED_F_TA_reduced
ren c2 JS_FLEX_SCHED_F_TA_unchanged
ren c3 JS_FLEX_SCHED_F_TA_increased
ren c4 JS_FLEX_SCHED_M_TA_reduced
ren c5 JS_FLEX_SCHED_M_TA_unchanged
ren c6 JS_FLEX_SCHED_M_TA_increased
ren c7 JS_FLEX_SCHED_P_TA_reduced
ren c8 JS_FLEX_SCHED_P_TA_unchanged
ren c9 JS_FLEX_SCHED_P_TA_increased
ren c10 JS_FLEX_SCHED_NP_TA_reduced
ren c11 JS_FLEX_SCHED_NP_TA_unchanged
ren c12 JS_FLEX_SCHED_NP_TA_increased
ren c13 JS_NIGHTS_REG_F_TA_reduced
ren c14 JS_NIGHTS_REG_F_TA_unchanged
ren c15 JS_NIGHTS_REG_F_TA_increased
ren c16 JS_NIGHTS_REG_M_TA_reduced
ren c17 JS_NIGHTS_REG_M_TA_unchanged
ren c18 JS_NIGHTS_REG_M_TA_increased
ren c19 JS_NIGHTS_REG_P_TA_reduced
ren c20 JS_NIGHTS_REG_P_TA_unchanged
ren c21 JS_NIGHTS_REG_P_TA_increased
ren c22 JS_NIGHTS_REG_NP_TA_reduced
ren c23 JS_NIGHTS_REG_NP_TA_unchanged
ren c24 JS_NIGHTS_REG_NP_TA_increased
ren c25 JS_L_HOURS_REG_F_TA_reduced
ren c26 JS_L_HOURS_REG_F_TA_unchanged
ren c27 JS_L_HOURS_REG_F_TA_increased
ren c28 JS_L_HOURS_REG_M_TA_reduced
ren c29 JS_L_HOURS_REG_M_TA_unchanged
ren c30 JS_L_HOURS_REG_M_TA_increased
ren c31 JS_L_HOURS_REG_P_TA_reduced
ren c32 JS_L_HOURS_REG_P_TA_unchanged
ren c33 JS_L_HOURS_REG_P_TA_increased
ren c34 JS_L_HOURS_REG_NP_TA_reduced
ren c35 JS_L_HOURS_REG_NP_TA_unchanged
ren c36 JS_L_HOURS_REG_NP_TA_increased
ren c37 JS_WEEKEND_F_TA_reduced
ren c38 JS_WEEKEND_F_TA_unchanged
ren c39 JS_WEEKEND_F_TA_increased
ren c40 JS_WEEKEND_M_TA_reduced
ren c41 JS_WEEKEND_M_TA_unchanged
ren c42 JS_WEEKEND_M_TA_increased
ren c43 JS_WEEKEND_P_TA_reduced
ren c44 JS_WEEKEND_P_TA_unchanged
ren c45 JS_WEEKEND_P_TA_increased
ren c46 JS_WEEKEND_NP_TA_reduced
ren c47 JS_WEEKEND_NP_TA_unchanged
ren c48 JS_WEEKEND_NP_TA_increased
ren c49 JS_LONG_FLEX_F_TA_reduced
ren c50 JS_LONG_FLEX_F_TA_unchanged
ren c51 JS_LONG_FLEX_F_TA_increased
ren c52 JS_LONG_FLEX_M_TA_reduced
ren c53 JS_LONG_FLEX_M_TA_unchanged
ren c54 JS_LONG_FLEX_M_TA_increased
ren c55 JS_LONG_FLEX_P_TA_reduced
ren c56 JS_LONG_FLEX_P_TA_unchanged
ren c57 JS_LONG_FLEX_P_TA_increased
ren c58 JS_LONG_FLEX_NP_TA_reduced
ren c59 JS_LONG_FLEX_NP_TA_unchanged
ren c60 JS_LONG_FLEX_NP_TA_increased
ren c61 JS_SUN_NIGHTS_F_TA_reduced
ren c62 JS_SUN_NIGHTS_F_TA_unchanged
ren c63 JS_SUN_NIGHTS_F_TA_increased
ren c64 JS_SUN_NIGHTS_M_TA_reduced
ren c65 JS_SUN_NIGHTS_M_TA_unchanged
ren c66 JS_SUN_NIGHTS_M_TA_increased
ren c67 JS_SUN_NIGHTS_P_TA_reduced
ren c68 JS_SUN_NIGHTS_P_TA_unchanged
ren c69 JS_SUN_NIGHTS_P_TA_increased
ren c70 JS_SUN_NIGHTS_NP_TA_reduced
ren c71 JS_SUN_NIGHTS_NP_TA_unchanged
ren c72 JS_SUN_NIGHTS_NP_TA_increased
